// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SuFood.Models
{
    public partial class Announcement
    {
        public int AnnouncementId { get; set; }
        public string AnnouncementContent { get; set; }
        public string AnnouncementStatus { get; set; }
        public DateTime AnnouncementStartDate { get; set; }
        public DateTime AnnouncementEndDate { get; set; }
        public byte[] AnnouncementImage { get; set; }
        public int AccountId { get; set; }

        public virtual Account Account { get; set; }
    }
}