// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SuFood.Models
{
    public partial class CouponUsedList
    {
        public int CouponUsedId { get; set; }
        public DateTime? CouponUsedOrNot { get; set; }
        public int? AccountId { get; set; }
        public int? CouponId { get; set; }

        public virtual Account Account { get; set; }
        public virtual Coupon Coupon { get; set; }
    }
}