// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SuFood.Models
{
    public partial class Discount
    {
        public int DiscountId { get; set; }
        public string DiscountDescription { get; set; }
        public string CreateAccount { get; set; }
        public decimal Discount1 { get; set; }
        public DateTime DiscountStartdate { get; set; }
        public DateTime DiscountEnddate { get; set; }
    }
}