// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SuFood.Models
{
    public partial class FreeChoiceProducts
    {
        public int ProductId { get; set; }
        public int PlanId { get; set; }
        public string ProductName { get; set; }
        public byte[] Img { get; set; }
        public string ProductDescription { get; set; }
        public int? ProductPrice { get; set; }

        public virtual FreeChoicePlans Plan { get; set; }
    }
}