// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SuFood.Models
{
    public partial class FreeChoicePlans
    {
        public FreeChoicePlans()
        {
            ProductsOfPlans = new HashSet<ProductsOfPlans>();
        }

        public int PlanId { get; set; }
        public string PlanName { get; set; }
        public string PlanDescription { get; set; }
        public int? PlanTotalCount { get; set; }
        public int? PlanCanChoiceCount { get; set; }
        public int? PlanPrice { get; set; }
        public bool? PlanStatus { get; set; }

        public virtual ICollection<ProductsOfPlans> ProductsOfPlans { get; set; }
    }
}