// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SuFood.Models
{
    public partial class OrdersDetails
    {
        public int? OrderId { get; set; }
        public string ProductName { get; set; }
        public int? UnitPrice { get; set; }
        public int? Quantity { get; set; }
        public int? CouponId { get; set; }
        public int OrdersDetailsId { get; set; }

        public virtual Orders Order { get; set; }
    }
}