// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SuFood.Models
{
    public partial class Orders
    {
        public Orders()
        {
            OrdersReview = new HashSet<OrdersReview>();
        }

        public int OrdersId { get; set; }
        public int SubTotal { get; set; }
        public int SubCost { get; set; }
        public double SubDiscount { get; set; }
        public string PaymentMethod { get; set; }
        public DateTime SetOrdersDatetime { get; set; }
        public string ShipAddress { get; set; }
        public string OrderStatus { get; set; }
        public int ShippingMethodId { get; set; }
        public string Status { get; set; }
        public int CustomerId { get; set; }
        public int CooponId { get; set; }
        public int DiscountId { get; set; }
        public int OrdersDetailsId { get; set; }

        public virtual ICollection<OrdersReview> OrdersReview { get; set; }
    }
}