// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SuFood.Models
{
    public partial class OrdersReview
    {
        public int ReviewId { get; set; }
        public int? RatingStar { get; set; }
        public string Comment { get; set; }
        public int OrdersId { get; set; }

        public virtual Orders Orders { get; set; }
    }
}