// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SuFood.Models
{
    public partial class ProductsOfPlans
    {
        public int PlanId { get; set; }
        public int ProductId { get; set; }
        public int? Price { get; set; }

        public virtual FreeChoicePlans Plan { get; set; }
        public virtual Products Product { get; set; }
    }
}