// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SuFood.Models
{
    public partial class Products
    {
        public Products()
        {
            ProductsOfPlans = new HashSet<ProductsOfPlans>();
            RetailsList = new HashSet<RetailsList>();
            ShoppingCart = new HashSet<ShoppingCart>();
            SubscribeList = new HashSet<SubscribeList>();
        }

        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string StockUnit { get; set; }
        public int StockQuantity { get; set; }
        public int Price { get; set; }
        public int Cost { get; set; }
        public string Category { get; set; }
        public byte[] Img { get; set; }
        public bool? IsHelpUchioce { get; set; }

        public virtual ICollection<ProductsOfPlans> ProductsOfPlans { get; set; }
        public virtual ICollection<RetailsList> RetailsList { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }
        public virtual ICollection<SubscribeList> SubscribeList { get; set; }
    }
}