// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SuFood.Models
{
    public partial class RecyleOrderDetails
    {
        public int RecyleOrderDetailsId { get; set; }
        public string ProductName { get; set; }
        public int? Quantity { get; set; }
        public int ReSubOrdersId { get; set; }

        public virtual RecyleSubscribeOrders ReSubOrders { get; set; }
    }
}