// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SuFood.Models
{
    public partial class RecyleSubscribeOrders
    {
        public int ReSubOrdersId { get; set; }
        public int ShipTotalFrequency { get; set; }
        public int ShipCumulativeFrequency { get; set; }
        public int SingleShipCost { get; set; }
        public int SingleShipDate { get; set; }
        public DateTime ShipStartDate { get; set; }
        public DateTime ShipEndDate { get; set; }
        public int OrdersId { get; set; }

        public virtual Orders Orders { get; set; }
    }
}