// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SuFood.Models
{
    public partial class ShoppingMethod
    {
        public string ShoppingMethodId { get; set; }
        public string Methods { get; set; }
        public int RetailsId { get; set; }
        public int SubscribeId { get; set; }
        public int Free2ChoiceId { get; set; }

        public virtual RetailsList Retails { get; set; }
        public virtual SubscribeList Subscribe { get; set; }
    }
}