// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SuFood.Models
{
    public partial class SubscribeList
    {
        public SubscribeList()
        {
            ShoppingMethod = new HashSet<ShoppingMethod>();
        }

        public int SubscribeId { get; set; }
        public int ProductId { get; set; }

        public virtual Products Product { get; set; }
        public virtual ICollection<ShoppingMethod> ShoppingMethod { get; set; }
    }
}